[package]
name = "release-profiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0 # 0 is default

[profile.release]
opt-level = 3 # 3 is default

[dependencies]
